### ISSUE TITLE
Plain text/md file instead of the database?

### ISSUE THREAD

**Issue by rseac** [darrikonn/td-cli#22]
Is it possible to use the markdown file instead of the database? This would be in line with todo-txt, and allow one to synchronize and edit on the cloud very easily?

**Comment by darrikonn** [comment]
`td-cli` uses `sqlite` which just reads and writes directly to ordinary disk files.
You can easily track that file with some cloud tool and synchronise it with all your computers/phones/tablets.

The database file can be located at `~/.config/td-cli/todo.db`

**Comment by darrikonn** [comment]
^ I personally use `Termux` on my Android phone to use `td-cli` on my phone. Not the best UX to use a `cli` on your phone, but a fun experiment :)

**Comment by rseac** [comment]
I think the real reason why a text file would help is that it would be cli/editor agnostic. If one had to just make some minor additions that simply using a text editor on the cloud would easily allow updating the items. In some ways it's one of the greatest strengths of todo-txt. 

I can't edit the todo.db using a text editor on the cloud ...?

**Comment by darrikonn** [comment]
Yeah I see what you mean.. sorry for the misunderstanding.

This task falls in line with the future goals that I see `td-cli` growing into.
I want to allow other developers to write custom plugins that `td-cli` could hook into.
Using a txt/md file instead of the database would result in a complete rewrite of all the service code, which is something that I won't do. However, when the plugin implementation is done, one could write a txt/md db plugin for `td-cli` and use that as it's database (which would come instead of the service).
Another such plugin (from another issue) would by to sync `td-cli` with Google Tasks api.
